### ISSUE TITLE
So im switching from nginx to apache2 sasm problem registration wont work.

### ISSUE THREAD

**Issue by magic-space** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#11]
# Query_time: 18.809801  Lock_time: 0.000054  Rows_sent: 1  Rows_examined: 14948935
# Rows_affected: 0  Bytes_sent: 97
use xyz_;
SET timestamp=1610783397;
select cluster from zone_grid_clusters zgc where zgc.zone_id = 1 and 10 > (select count(*) from zone_grid_cluster_nodes zgcn where zgcn.cluster = zgc.cluster and zgcn.zone_id = 1 and zgcn.user_id is not null limit 1) order by zgc.cluster asc limit 1;

**Comment by magic-space** [comment]
i cant see any error on the page.

**Comment by nenuadrian** [comment]
Hey magic-space, long time, but if you could try via the newly available setup process and re-submit the bug, I will take a look and let you know 

It should all work on apache based based webservers which process the .htaccess
