### ISSUE TITLE
Bug vendor

### ISSUE THREAD

**Issue by Link0Darck** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#15]
Hello,
I tried to install it but here is the problem
Sincerely
`
Warning: require_once(../includes/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/Jeux/Secret-Republic-V3/index.php on line 2

Fatal error: require_once(): Failed opening required '../includes/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/Jeux/Secret-Republic-V3/index.php on line 2`

**Comment by nenuadrian** [comment]
composer install

Please follow the README instruction - the process has been simplified but you will have to install composer on your own and run this command, and create a database before using the automated process which creates the tables and sets up your admin account
