### ISSUE TITLE
Database error?

### ISSUE THREAD

**Issue by SKSaki** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#19]
![Screenshot_20220804-072422_Brave](https://user-images.githubusercontent.com/25939321/182762903-7e51d446-e07b-4991-a8e4-af1270fac5a6.jpg)

**Comment by nenuadrian** [comment]
Hey!

Try running: SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

In phpmyadmin or via command line. The SQL script already has it but perhaps it doesn't run it correctly! 

https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/blob/master/includes/DB.sql

**Comment by SKSaki** [comment]
Hi, i wrote on your instagram. I am @ogshxde
The problem is that phpmyadmin errors it as well, and my hosting service removed the line because they deemed it as invalid syntax and it worked afterwards. I am not sure what that command does, but it doesn't kiss very well with Ultahost's structure

**Comment by nenuadrian** [comment]
Hey,

Alternative would be identifying exactly what of my old SQL or the SQL library used creates this problem

I’m not sure when I’ll be able to have a look but I’ll surely let you know and if you figure it out please make a PR!

**Comment by SKSaki** [comment]
For now the solution is to remove the line from the .db file. 
It will still import it and no error was thrown. But it seems the website keeps reloading to index.php on any page. The adress bar would be like example.com/rankings but instead, the index.php is shown. Which i am not sure how to fix.

**Comment by nenuadrian** [comment]
I see, thank you, I'll remove from SQL file and add it to the README for those who see that error instead.

As far as the redirect, I suspect that may be the .htaccess file, can you please check if it got uploaded to your webhost correctly? If you use a Mac, it might not show the file to you if you drag and dropped, you can create a new file via your FTP client/file manager called .htaccess and just copy the contents in from github? 

But yeah let me know if that's not the issue. Also ensure your host will process .htaccess files or if it needs something else (e.g. does it use Apache)

https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/blob/master/public_html/.htaccess

**Comment by SKSaki** [comment]
The .htaccess is on the server on public_html/public_html

I had to make a secondary folder and put that as home folder in my control panel because the /root of the subdomain i use it on is not writtable

**Comment by nenuadrian** [comment]
If you’re happy emailing me login details to Adrian.nenu@gmail.com I can have a look later today?

**Comment by nenuadrian** [comment]
https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/e781c31e6cac44fc79bd5d6f71df7560391d1ef5

This seems to resolve it on your host - there may be edge cases but seems to work as far as I could tell!
