### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by bornhaeusser** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#2]
Fatal error: Call to a member function isSMTP() on null in /volume1/web/game/hacking/includes/class/alpha.class.php on line 50

**Comment by nenuadrian** [comment]
Maybe now? 

Did that on the fly as this code is very old so I added dependency management and all these libraries ad-hock before making it available 

Will be trying to make time to make it more stable and usable, thanks for reporting issues, keep at it ;)

**Comment by nenuadrian** [comment]
Hi - fixed a few issues today - please recreate if this is still an issue
