### ISSUE TITLE
Failed opening required "contants/abilities.php"

### ISSUE THREAD

**Issue by SKSaki** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#24]
https://hrpg.lscult.com/admin/view/data/load/abilities/toLevel/30/userLevel/90  < here is the error.

**Comment by nenuadrian** [comment]
https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/98773970327080eaf5144bb9411d291fd4338b16
