### ISSUE TITLE
Weird long URL

### ISSUE THREAD

**Issue by SKSaki** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#25]
https://hrpg.lscult.com/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/4/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/4/page/5/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/4/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/4/page/5/page/1/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/4/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/4/page/5/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/4/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/page/2/page/alpha_coins/history/alpha_coins/history/archive/page/alpha_coins/history/alpha_coins/history/archive/

Also it seems the history is not shown properly :))
There is nothing there
Steps to replicate: Go to base url, click on the page numbers. Slowly it will cause it to happen.

**Comment by nenuadrian** [comment]
https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/e2d7ef07038e56ffb2df57af53c36e09566b4583
