### ISSUE TITLE
Class server not found.

### ISSUE THREAD

**Issue by SKSaki** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#26]
https://hrpg.lscult.com/servers/build/hell < have components in your storage and click build. This error pops up.

**Comment by nenuadrian** [comment]
This is due to incorrect includes after past refactoring 

Resolved on your host

**Comment by nenuadrian** [comment]
https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/1a494b50cefb896d9c7cd121dee1c77e77b19438
https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/b746b08140450f58e6512be051788b5f8d73cfc6
