### ISSUE TITLE
Blank page i suppose

### ISSUE THREAD

**Issue by SKSaki** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#28]
https://hrpg.lscult.com/zones  < displays no info on the page

**Comment by nenuadrian** [comment]
This SQL was missing from the import, please execute manually from your side, I have fixed the repository: 

https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/a924035f57caba53ee68f387496272751c08335d

INSERT INTO `zones` (`id`, `nrm`, `president`, `data`, `status`, `rank`, `next_elections`, `market_tax`, `defense`, `hack`, `vault`, `fmarket_tax`, `min_defence`, `min_finance`) VALUES (1,480,559,NULL,NULL,0,0,1,0,0,436,2,588,836),(2,60,38,NULL,NULL,0,0,1,0,0,23.05,2,0,0),(3,67,38,NULL,NULL,0,0,1,0,0,21666.12,2,0,0),(4,55,38,NULL,NULL,0,0,1,0,0,22.53,2,0,0),(5,55,1510,NULL,NULL,0,0,1,0,0,31.8,2,0,0),(6,152,52,NULL,NULL,0,0,1,0,0,41.8,2,0,0);
