### ISSUE TITLE
database_info.php

### ISSUE THREAD

**Issue by soireemb** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#3]
I receive this error on php 7.1.7:

> Warning: require(/includes/database_info.php): failed to open stream: No such file or directory in C:\MAMP\includes\class\cardinal.php on line 29
> 
> Fatal error: require(): Failed opening required '/includes/database_info.php' (include_path='.;C:\php\pear') in C:\MAMP\includes\class\cardinal.php on line 29

When I use an older php version (e.g. 5.6.0) it seems to work, but I receive different errors instead. The file is there, at the correct location, yet this part doesn't seem to work.  The error on 5.6.0 is:

> Fatal error: Uncaught --> Smarty: Unable to load template 'file:home/main_stats.tpl' <-- thrown in C:\MAMP\includes\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php on line 185
> 
> Fatal error: Uncaught --> Smarty: Unable to load template 'file:pages/error.tpl' <-- thrown in C:\MAMP\includes\vendor\smarty\smarty\libs\sysplugins\smarty_internal_template.php on line 185

**Comment by nenuadrian** [comment]
I'll check that out this weekend

**Comment by wumix** [comment]
and now you have checked? i have the same problem

**Comment by nenuadrian** [comment]
Instructions need to be followed per README to create the file based on the sample one
