### ISSUE TITLE
i cant add hdd to my server

### ISSUE THREAD

**Issue by fisher762** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#39]
hello
when i buy ram and hdd and other parts for the server i cant connect the hdd and server together .. the slot is empty always 
![image](https://user-images.githubusercontent.com/410750/190326396-d7306ace-ef4d-4314-994f-37c2fac4aff4.png)

**Comment by nenuadrian** [comment]
Thank you for the report @fisher762 - will have a look and get back to you this week

**Comment by nenuadrian** [comment]
So I think you probably got as I did an error when building the server, along the lines of an issue with recomputeServerResources

This causes the server config to be corrupted in the DB - so the slot doesn't exist

I've put this fix: https://github.com/nenuadrian/Secret-Republic-Hacking-Browser-Game-V3/commit/9752eaac963e319dca190d4b6793b24ad24fd73d

If you apply same and try it then it should work now
