### ISSUE TITLE
Most is Working are not all is working

### ISSUE THREAD

**Issue by wumix** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#5]
you can see my game at http://secretrepublic.esy.es/

Register and the most of all other Pages are working.

FAQ is not working
Premium Section is not Working.
and meny more.

Adrian can you help me ore not??

**Comment by nenuadrian** [comment]
Hey Wumix

There are issues with -'s and _ 

Fixed FAQ for example, many of the pages like beginner intro fixed too

Please open new item with list of other isssues
