### ISSUE TITLE
Nginx installation 

### ISSUE THREAD

**Issue by magic-space** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#6]
Hi sounds good that you are back.
ᛁ love this game after long time ᛁ installed this game with little bugs. 

Now how to set nginx rewrite rules?

And here is my error log.

2021/01/03 17:21:21 [error] 33041#0: *78405 open() "/www/wwwroot/secret-republic.ddnss.de/public_html/layout/css/Abel.woff2" failed (2: No such file or directory), client: 87.168.60.130, server: secret-republic.ddnss.de, request: "GET /layout/css/Abel.woff2 HTTP/2.0", host: "secret-republic.ddnss.de", referrer: "https://secret-republic.ddnss.de/layout/css/custom.css?t=fffff"
2021/01/03 17:21:24 [error] 33041#0: *78405 open() "/www/wwwroot/secret-republic.ddnss.de/public_html/register" failed (2: No such file or directory), client: 87.168.60.130, server: secret-republic.ddnss.de, request: "GET /register HTTP/2.0", host: "secret-republic.ddnss.de", referrer: "https://secret-republic.ddnss.de/"
2021/01/03 17:22:00 [error] 33281#0: *78408 open() "/www/wwwroot/secret-republic.ddnss.de/public_html/layout/css/Abel.woff2" failed (2: No such file or directory), client: 87.168.60.130, server: secret-republic.ddnss.de, request: "GET /layout/css/Abel.woff2 HTTP/2.0", host: "secret-republic.ddnss.de", referrer: "https://secret-republic.ddnss.de/layout/css/custom.css?t=fffff"
2021/01/03 17:22:04 [error] 33281#0: *78408 open() "/www/wwwroot/secret-republic.ddnss.de/public_html/register" failed (2: No such file or directory), client: 87.168.60.130, server: secret-republic.ddnss.de, request: "GET /register HTTP/2.0", host: "secret-republic.ddnss.de", referrer: "https://secret-republic.ddnss.de/"
2021/01/03 19:06:37 [error] 62196#0: *78423 open() "/www/wwwroot/secret-republic.ddnss.de/public_html/register" failed (2: No such file or directory), client: 87.168.60.130, server: secret-republic.ddnss.de, request: "GET /register HTTP/2.0", host: "secret-republic.ddnss.de", referrer: "https://secret-republic.ddnss.de/"

**Comment by magic-space** [comment]
I'm using php3

**Comment by magic-space** [comment]
![Uploading Screenshot_20210103_214243_com.sec.android.app.sbrowser.jpg…]()

**Comment by nenuadrian** [comment]
Hey @magic-space 

Thanks for trying it out - I don't actually have the nginx rules, but any webhost would probably have ability to host with apache, and locally it should be trivial for you to do so, if you use a VPS that might be a bit harder etc just cause you'd already have a setup

I don't think I'll have the time to investigate converting to nginx any time soon, but if you could first, please do check it in github, I will create a contributors list if you do so in the README!

You can also read the htaccess and see how it rewrites and access the URLs accordingly, but of course the hard coded URLs in the templates will point to the ones it expects will be rewritten, and layouts files etc may or may not be rendered properly due to that

Have you tried something like? https://winginx.com/en/htaccess

I'm highly doubtful it works

**Comment by nenuadrian** [comment]
I think I see you may already have figured it out? :) secret-republic.ddnss.de seems to work

**Comment by nenuadrian** [comment]
Also have just done some cleanups, might want to get latest code, especially for a typo in organization.php - there may be others as I globally replaced include("") with require(', and there seem to be some unmatched single/double quotes in some places

**Comment by magic-space** [comment]
Perfect yes I'm figured out the nginx configuration. And seems to be working.

Only when ᛁ finish the registration but not working.

**Comment by magic-space** [comment]
So ᛁ will upload the complete include folder and templates.
Next question rewrite base to public_html or other folder?

Thank you for your support. 

ᛁ will create in my idlegames.ddnss.de community a section German and English for this and game and v4 to support and modifications.

ᛁ love this game. 

It's very good work and looks very nice.

**Comment by nenuadrian** [comment]
Awesome - I've added you as a colaborator, create any branches you want :)
public_html can be renamed to anything what so ever, your webserver needs to present that folder that's it, most php files are outside that directory for security so they're not accessible via URL, same for templates

**Comment by nenuadrian** [comment]
Please close this issue if resolved

**Comment by wumix** [comment]
Registration not work ᛁ can't see no errors.

Nenu Adrian <notifications@github.com> schrieb am Mi., 6. Jan. 2021, 21:54:

**Comment by nenuadrian** [comment]
If you send me FTP details at adrian.nenu@gmail.com and the link - I can take a look
