### ISSUE TITLE
My friend Registration dont work....

### ISSUE THREAD

**Issue by magic-space** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#9]
Here is your community:
[IdleGames SRHB Community ](http://idlegames.ddnss.de/index.php?r=space%2Fspace%2Fhome&cguid=8b4c79d7-3d8d-46b1-9316-086d89c0d805)

I cant register i Upload all files and register will not working please help me

**Comment by nenuadrian** [comment]
Hey - sorry what's the link above? Since that's not the game

**Comment by magic-space** [comment]
gamelink [Secret-Republic Game Link](https://secret-republic.ddnss.de/)


This link is your Support Community. [IdleGames](https://idlegames.ddnss.de)

**Comment by magic-space** [comment]
![srhb](https://user-images.githubusercontent.com/67586093/104059483-ba567e00-51f5-11eb-9443-56fd61545d6c.jpg)

**Comment by nenuadrian** [comment]
What have you tried to debug it? There will be many issues I believe so it would be good to figure out how to debug them

The registration seemed to work on the demo site and that’s the exact some code no changes

I can take a look if you could give me FTP access so I can remove maybe some of the error handling or mess around with the register part to figure it out but I’d recommend you have a go at it

**Comment by nenuadrian** [comment]
adrian.nenu@gmail.com you can send them there if you want

**Comment by nenuadrian** [comment]
What version of PHP are you running btw?

**Comment by magic-space** [comment]
i use php 7.3

**Comment by nenuadrian** [comment]
We caught up offline and decided this is likely due to nginx - please submit your nginx file if good / reopen if issue occurs once you try apache where .htaccess works
